displayName=No GE Inventory Blink
author=osrshool22
description=Stops the inventory from blinking/flashing while the Grand Exchange window is open
tags=ge,interface,blink,flash,inventory,visual
plugins=net.runelite.client.plugins.nogeblink.NoGEInventoryBlinkPlugin
version=
build=standard